name: image_cropper_platform_interface
description: A common platform interface for the image_cropper plugin.
repository: https://github.com/hnvn/flutter_image_cropper
version: 7.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
